Fix compile error introduced in 3.1.0-alpha.5
When compiled with LDC 1.22.0, this resulted in these rather obscure error messages:
```
sdl_types.d(792,1): Error: no property max for type string, perhaps import std.algorithm; is needed?
sdl_types.d(841,78): Error: incompatible types for ("SDL_VIDEO_MAC_FULLSCREEN_SPACES") + (1): string and int
```